export const parameters =[
    {
        "Index":0,
        "key":"gaussianElimination",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },

    {
        "Index":1,
        "key":"totalPivoting",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":2,
        "key":"parcialPivoting",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":3,
        "key":"incrementalSearch",
        "parameters":{
            "f":"function",
            "x0":"number",
            "deltaX":"number",
            "n":"number"
        }
    },
    {
        "Index":4,
        "key":"bisection",
        "parameters":{
            "f":"function",
            "a":"number",
            "b":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":5,
        "key":"falsePosition",
        "parameters":{
            "f":"function",
            "a":"number",
            "b":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":6,
        "key":"newton",
        "parameters":{
            "f":"function",
            "f1":"function",
            "x0":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":7,
        "key":"staticPoint",
        "parameters":{
            "f1":"function",
            "g":"function",
            "x0":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":8,
        "key":"secant",
        "parameters":{
            "f":"function",
            "x0":"number",
            "x1":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":9,
        "key":"multipleRoots",
        "parameters":{
            "h":"function",
            "dh1":"function",
            "dh2":"function",
            "x0":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":10,
        "key":"LUsimple",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":11,
        "key":"LUparcial",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":12,
        "key":"crout",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":13,
        "key":"doolittle",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },
    {
        "Index":14,
        "key":"cholesky",
        "parameters":{
            "A":"matrix",
            "b":"matrix"
        }
    },

    {
        "Index":15,
        "key":"jacobi",
        "parameters":{
            "A":"matrix",
            "b":"matrix",
            "x0":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":16,
        "key":"gauss-seidel",
        "parameters":{
            "A":"matrix",
            "b":"matrix",
            "x0":"number",
            "tol":"number",
            "n":"number"
        }
    },
    {
        "Index":17,
        "key":"sor",
        "parameters":{
            "A":"matrix",
            "b":"matrix",
            "x0":"number",
            "w":"number",
            "tol":"number",
            "n":"number"
        }
    },

    {
        "Index":18,
        "key":"vandermonde",
        "parameters":{
            "x":"table",
            "y":"table",
        }
    },

    {
        "Index":19,
        "key":"newtonInterpolation",
        "parameters":{
            "x":"table",
            "y":"table",
        }
    },
    {
        "Index":20,
        "key":"spline1",
        "parameters":{
            "x":"table",
            "y":"table",
        }
    },
    {
        "Index":21,
        "key":"spline2",
        "parameters":{
            "x":"table",
            "y":"table",
        }
    },
    {
        "Index":22,
        "key":"spline3",
        "parameters":{
            "x":"table",
            "y":"table",
        }
    },
    
  
    
        
    
]